import { precacheAndRoute } from 'workbox-precaching';

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('fetch', (event) => {
    if (event.request.method === 'POST' && event.request.url.includes('/share-target')) {
        event.respondWith(
            (async () => {
                try {
                    const formData = await event.request.formData();
                    // Some apps use 'files', others 'media', or 'image'
                    const file = formData.get('files') || formData.get('media') || formData.get('image');

                    if (file) {
                        console.log('Shared file received:', file.name, file.type);
                        const cache = await caches.open('shared-media');
                        await cache.put('shared-image', new Response(file));
                    }

                    // Success redirect
                    return Response.redirect('/analysis?shared-image=true', 303);
                } catch (err) {
                    console.error('Share Target Error:', err);
                    // Fallback redirect on error to prevent broken page
                    return Response.redirect('/analysis?error=share_failed', 303);
                }
            })()
        );
    }
});

self.addEventListener('install', (event) => {
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});
