import { precacheAndRoute } from 'workbox-precaching';

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('fetch', (event) => {
    if (event.request.method === 'POST' && event.request.url.includes('/share-target')) {
        event.respondWith(
            (async () => {
                const formData = await event.request.formData();
                const file = formData.get('files');

                if (file) {
                    const cache = await caches.open('shared-media');
                    await cache.put('shared-image', new Response(file));
                }

                return Response.redirect('/analysis?shared-image=true', 303);
            })()
        );
    }
});

self.addEventListener('install', (event) => {
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});
